"""Tushare adapter package."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from data_platform.adapters.tushare.assets import (
    EVENT_METADATA_FIELDS,
    REFERENCE_DATA_IDENTITY_FIELDS,
    TUSHARE_ADJ_FACTOR_ASSET,
    TUSHARE_ADJ_FACTOR_ASSET_NAME,
    TUSHARE_ANNS_ASSET,
    TUSHARE_ANNS_ASSET_NAME,
    TUSHARE_ASSETS,
    TUSHARE_DAILY_ASSET,
    TUSHARE_DAILY_ASSET_NAME,
    TUSHARE_DAILY_BASIC_ASSET,
    TUSHARE_DAILY_BASIC_ASSET_NAME,
    TUSHARE_DISCLOSURE_DATE_ASSET,
    TUSHARE_DISCLOSURE_DATE_ASSET_NAME,
    TUSHARE_DIVIDEND_ASSET,
    TUSHARE_DIVIDEND_ASSET_NAME,
    TUSHARE_INDEX_BASIC_ASSET,
    TUSHARE_INDEX_BASIC_ASSET_NAME,
    TUSHARE_INDEX_CLASSIFY_ASSET,
    TUSHARE_INDEX_CLASSIFY_ASSET_NAME,
    TUSHARE_INDEX_DAILY_ASSET,
    TUSHARE_INDEX_DAILY_ASSET_NAME,
    TUSHARE_INDEX_MEMBER_ASSET,
    TUSHARE_INDEX_MEMBER_ASSET_NAME,
    TUSHARE_INDEX_WEIGHT_ASSET,
    TUSHARE_INDEX_WEIGHT_ASSET_NAME,
    TUSHARE_MONTHLY_ASSET,
    TUSHARE_MONTHLY_ASSET_NAME,
    TUSHARE_NAMECHANGE_ASSET,
    TUSHARE_NAMECHANGE_ASSET_NAME,
    TUSHARE_SHARE_FLOAT_ASSET,
    TUSHARE_SHARE_FLOAT_ASSET_NAME,
    TUSHARE_STOCK_BASIC_ASSET,
    TUSHARE_STOCK_BASIC_ASSET_NAME,
    TUSHARE_STOCK_BASIC_FIELDS,
    TUSHARE_STOCK_BASIC_SCHEMA,
    TUSHARE_STOCK_COMPANY_ASSET,
    TUSHARE_STOCK_COMPANY_ASSET_NAME,
    TUSHARE_STK_HOLDERNUMBER_ASSET,
    TUSHARE_STK_HOLDERNUMBER_ASSET_NAME,
    TUSHARE_SUSPEND_D_ASSET,
    TUSHARE_SUSPEND_D_ASSET_NAME,
    TUSHARE_TRADE_CAL_ASSET,
    TUSHARE_TRADE_CAL_ASSET_NAME,
    TUSHARE_WEEKLY_ASSET,
    TUSHARE_WEEKLY_ASSET_NAME,
)

if TYPE_CHECKING:
    from data_platform.adapters.tushare.adapter import AdapterConfigError, TushareAdapter


def __getattr__(name: str) -> Any:
    if name == "AdapterConfigError":
        from data_platform.adapters.tushare.adapter import AdapterConfigError

        return AdapterConfigError
    if name == "TushareAdapter":
        from data_platform.adapters.tushare.adapter import TushareAdapter

        return TushareAdapter
    raise AttributeError(name)


__all__ = [
    "AdapterConfigError",
    "EVENT_METADATA_FIELDS",
    "REFERENCE_DATA_IDENTITY_FIELDS",
    "TUSHARE_ADJ_FACTOR_ASSET",
    "TUSHARE_ADJ_FACTOR_ASSET_NAME",
    "TUSHARE_ANNS_ASSET",
    "TUSHARE_ANNS_ASSET_NAME",
    "TUSHARE_ASSETS",
    "TUSHARE_DAILY_ASSET",
    "TUSHARE_DAILY_ASSET_NAME",
    "TUSHARE_DAILY_BASIC_ASSET",
    "TUSHARE_DAILY_BASIC_ASSET_NAME",
    "TUSHARE_DISCLOSURE_DATE_ASSET",
    "TUSHARE_DISCLOSURE_DATE_ASSET_NAME",
    "TUSHARE_DIVIDEND_ASSET",
    "TUSHARE_DIVIDEND_ASSET_NAME",
    "TUSHARE_INDEX_BASIC_ASSET",
    "TUSHARE_INDEX_BASIC_ASSET_NAME",
    "TUSHARE_INDEX_CLASSIFY_ASSET",
    "TUSHARE_INDEX_CLASSIFY_ASSET_NAME",
    "TUSHARE_INDEX_DAILY_ASSET",
    "TUSHARE_INDEX_DAILY_ASSET_NAME",
    "TUSHARE_INDEX_MEMBER_ASSET",
    "TUSHARE_INDEX_MEMBER_ASSET_NAME",
    "TUSHARE_INDEX_WEIGHT_ASSET",
    "TUSHARE_INDEX_WEIGHT_ASSET_NAME",
    "TUSHARE_MONTHLY_ASSET",
    "TUSHARE_MONTHLY_ASSET_NAME",
    "TUSHARE_NAMECHANGE_ASSET",
    "TUSHARE_NAMECHANGE_ASSET_NAME",
    "TUSHARE_SHARE_FLOAT_ASSET",
    "TUSHARE_SHARE_FLOAT_ASSET_NAME",
    "TUSHARE_STOCK_BASIC_ASSET",
    "TUSHARE_STOCK_BASIC_ASSET_NAME",
    "TUSHARE_STOCK_BASIC_FIELDS",
    "TUSHARE_STOCK_BASIC_SCHEMA",
    "TUSHARE_STOCK_COMPANY_ASSET",
    "TUSHARE_STOCK_COMPANY_ASSET_NAME",
    "TUSHARE_STK_HOLDERNUMBER_ASSET",
    "TUSHARE_STK_HOLDERNUMBER_ASSET_NAME",
    "TUSHARE_SUSPEND_D_ASSET",
    "TUSHARE_SUSPEND_D_ASSET_NAME",
    "TUSHARE_TRADE_CAL_ASSET",
    "TUSHARE_TRADE_CAL_ASSET_NAME",
    "TUSHARE_WEEKLY_ASSET",
    "TUSHARE_WEEKLY_ASSET_NAME",
    "TushareAdapter",
]
